name: cropmask
channels:
  - conda-forge
dependencies:
  - python=3.6
  # Core scientific python
  - numpy
  - matplotlib
  - pyqt
  - xlrd # for excel sheets in pandas
  - scipy
  - scikit-image
  - xarray
  - dask

# Mask_RCNN requirements
  - Pillow
  - cython
  - matplotlib
  - scikit-image
  - opencv
  - h5py
  - IPython[all]

  # Geo stuff
  - rasterstats
  - rioxarray
  - geocube
  - geopy
  - cartopy
  - geopandas
  - rasterio
  - contextily
  - pysal
  - pyproj
  - folium
  - gdal
  - libgdal
  - kealib
  - geojson

  # Other stuff
  - yaml

  - pip:
      - imgaug # for mrcnn
      - us
      - graphviz
      - git+git://github.com/waspinator/coco.git@2.1.0
      - git+git://github.com/waspinator/pycococreator.git@0.2.0
