name: cropmask
channels:
  - conda-forge
dependencies:
  - python=3.6
  # Core scientific python
  - numpy
  - matplotlib
  - pyqt
  - seaborn
  - xlrd # for excel sheets in pandas
  - scipy
  - scikit-image
  - xarray
  - dask

# Mask_RCNN requirements
  - Pillow
  - cython
  - matplotlib
  - scikit-image
  - keras-gpu>=2.2.2
  - opencv
  - h5py
  - IPython[all]

  # Geo stuff
  - rasterstats
  - geopy
  - cartopy
  - geopandas
  - rasterio
  - contextily
  - pysal
  - pyproj
  - folium
  - gdal
  - libgdal
  - kealib
  - geojson

  # Other stuff
  - yaml

  - pip:
      - imgaug # for mrcnn
      - rioxarray>=0.0.9
      - us
      - graphviz
      - tensorflow-gpu==1.13.1
