dirs:
    root: /datadrive
    dataset: test-ard-june-sept-nirrg # rename this based on where the folders with imagery and labels are located
landsat_bands_to_include:
    - blue: false
    - green: true
    - red: true
    - near-IR : true
seed: 42
