dirs:
    root: /datadrive
    dataset: test-ard-june-sept-rgb-jpeg-split-geo-128 # rename this based on where the folders with imagery and labels are located
landsat_bands_to_include:
    - blue: true
    - green: true
    - red: true
    - near-IR : false
seed: 42
