dirs:
    root: /datadrive
    dataset: test-ard-june-sept-rgb # rename this based on the imagery and labels
landsat_bands_to_include:
    - blue: true
    - green: true
    - red: true
    - near-IR : false
image_vals:
    dataset_name: "landsat-5"
    grid_size: 512 # in pixel units
    usable_thresh: .02 #image must have no more than this percentage of values that are zero from either clouds or no_data (tile edges)
    split: .10 # the proportion of samples that will be used for testing
label_vals:
    ag_class_int: 1 # TO DO # if there are more than one classes, ag_class_int is the integer label for the class that will be negative buffered and size filtered'
    small_area_filter: 3600 # in area meters, removes fields with area less than 100 meters from labels 
